### ISSUE TITLE
Scss modules?

### ISSUE THREAD

**Issue by theklr** [j1mc/bulma-scss#11]
Just checking if there's any intention of moving this towards the [sass module pattern](https://css-tricks.com/introducing-sass-modules/)?  No pressure, just checking on future plans. Thanks for the great work.

**Comment by j1mc** [comment]
Hi - thanks for the suggestion. I'm not familiar with this newer approach, but can take a look at it.

Would this cause inter-operability problems for people's existing projects when they upgrade, or would the change be transparent to them?

**Comment by theklr** [comment]
It probably would since `@use` and `@forward` are fairly new.

**Comment by j1mc** [comment]
In thinking about this, I think I'd prefer to keep this project a 'vanilla' implementation of Bulma, and not implement any new features that may break things for other people at this time. I hope that's okay.
If the approach you mention gets more widely adopted, I'd be willing to accept patches for it, though. Thank you for bringing it up and suggesting it.
