### ISSUE TITLE
Bulma extensions

### ISSUE THREAD

**Issue by deflektor-de** [j1mc/bulma-scss#12]
It would be great, if you also provide the official bulma extensions!

**Comment by j1mc** [comment]
I can look into this as a side project. It should be simple to do. I will comment here if / when I get to it.

**Comment by j1mc** [comment]
I know I could leave this issue open, but I know that I'm not going to have the time for this - at least in any foreseeable future.
The script for converting the primary Bulma SASS files to SCSS is available in my gist. I'm sure that someone could modify it for any Bulma extensions if they wanted to.
With that ... while I thank you for the suggestion, I'm going to close this for now. I would accept patches if someone else wanted to do the work for this, but it is probably better off in a separate git project.
