### ISSUE TITLE
compile fia

### ISSUE THREAD

**Issue by devmikromike** [j1mc/bulma-scss#16]

**Comment by devmikromike** [comment]
Hello 

I tried to install this package to Laravel 7.
installed by command: npm install bulma-scss --dev
 
ran:  npm run dev
I got error:

" Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: $n: Invalid index 2 for a list with 1 elements.
    ╷
162 │    $color-invert: nth($pair, 2);      "

thanks Mika.

**Comment by j1mc** [comment]
Hi - I'm seeing this now. Is there a reason for passing the `--dev` flag here?  I don't have a development branch of this project.

Also, it seems as though the issue is with `./node_modules/sass-loader/dist/cjs.js`, which is not part of this project.
