### ISSUE TITLE
<3

### ISSUE THREAD

**Issue by benfavre** [j1mc/bulma-scss#2]
<3

**Comment by j1mc** [comment]
Am I supposed to close this issue?  : )

**Comment by j1mc** [comment]
I will let the heart issue stay open.  : )

**Comment by reld** [comment]
Thanks for doing the port!
I was about to do one myself. Good Thing I did a search first 👍 
Cheers!

**Comment by Arstman** [comment]
<3 & thanks

**Comment by DimitarChristoff** [comment]
👍 

Hah - https://github.com/DimitarChristoff/bulma/tree/scss - did that ages ago thinking it can be PR'd. Glad I am not the only one, as I have not kept mine upto date.

**Comment by code-man** [comment]
Awesome 👍

**Comment by elkd** [comment]
> <3

I also had to google what does <3 mean😀, maybe design is not my thing but yay I <3 this thing❤️

**Comment by superbiche** [comment]
<3 very much

**Comment by florentpastor-wk** [comment]
More <3!

**Comment by themodernpk** [comment]
<3!

**Comment by gabrielgodoy** [comment]
<3

**Comment by j1mc** [comment]
I appreciate keeping our hearts open for this project for so many years. With Bulma's 1.0 release, Bulma now natively supports SCSS syntax, so this Bulma-SCSS project is no longer needed. I am archiving the project, but the code will remain available so as to not break any downstream dependencies.
