### ISSUE TITLE
Only need level and columns

### ISSUE THREAD

**Issue by ohabash** [j1mc/bulma-scss#21]
Thank you for sharing this port!

Can you instruct me how to include only the level? I put the following in my scss

`@import 'bulma-scss/components/level';`

but i get the compile error 

>ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: The target selector was not found.
Use "@extend %block !optional" to avoid this error.
  ╷
6 │   @extend %block;
  │   ^^^^^^^^^^^^^^

is there a base file to import?

**Comment by daaain** [comment]
Haven't tried so just guessing, but maybe you need to import `utilities/_extends.scss` first?

See: https://github.com/j1mc/bulma-scss/blob/f2a8a53dfb1ee96cd011607605ee59bb487c8068/utilities/_extends.scss#L15-L17
