### ISSUE TITLE
Active development?

### ISSUE THREAD

**Issue by scriptcoded** [j1mc/bulma-scss#3]
Is this package still under active development? We're planning on using this in a production application, and would still like to remain up to date with the latest Bulma features. :smiley:

**Comment by j1mc** [comment]
Hello, yes! I do actively maintain this project. However, I have only updated it when there is a formal Bulma release (see: https://github.com/jgthms/bulma/releases ).

When the Bulma project makes a release, I make a release, too. If you want to use this in production, I might recommend going off of the releases that I make ( https://github.com/j1mc/bulma-scss/releases ). This will allow you to keep your production setup pointed to a stable release while you do testing on the latest-and-greatest release.

If there is a need, I could see about creating a separate branch which follows Bulma master (i.e., which includes updates in master which are not yet part of a formal Bulma release). Let me know if that's what you're thinking or if you only want to track the main releases from Bulma.

Cheers.

**Comment by scriptcoded** [comment]
Wonderful! One thing that came to mind was automating the build using something CircleCI. Should I make a PR for that perhaps?

**Comment by j1mc** [comment]
I'm open to using CircleCI, though I haven't used it in the past. Feel free to make a pull request if you'd like for some CircleCI-foo to be included as part of the project.

Also, based on my prior comment, unless I hear otherwise I'll continue to only update this repo when the Bulma project makes a formal release.

**Comment by scriptcoded** [comment]
Absolutely :) I'll se if I can squeeze it in when I've got some time left over. Does updating include mergine pull requests?

**Comment by j1mc** [comment]
If you have a working pull request for CircleCI, I would merge it right away / wouldn't wait for the next release.  : )

**Comment by j1mc** [comment]
I'm going to close this issue for now, but feel free to comment on it further if you need anything else.
