### ISSUE TITLE
NPM support?

### ISSUE THREAD

**Issue by jacobslusser** [j1mc/bulma-scss#5]
Could NPM support (i.e. package.json file) be added?

**Comment by j1mc** [comment]
I've just started a new job, so don't have a great deal of time for this now, but would accept patches for this. I may get around to it eventually, but am not sure.
I know there's already a [bulma-scss npm package](https://www.npmjs.com/package/bulma-scss), but it looks to be out of date. If you need something soon, it might be worth pinging the maintainers of that npm package to update their version.

**Comment by j1mc** [comment]
The main bulma-scss project doesn't include an 'issue tracker' on github, but I've commented on an [existing pull-request](https://github.com/CyCoreSystems/bulma/pull/2#issuecomment-471629592), asking them to update their package and offering to have it based off of this repo.

I'll report-back if they respond.

**Comment by jacobslusser** [comment]
Okay. Thanks for responding so quickly. If I become available to send you a PR I would be happy to.
