### ISSUE TITLE
Can you publish it to npm?

### ISSUE THREAD

**Issue by ediopia** [j1mc/bulma-scss#6]
Can you publish it to npm?

**Comment by j1mc** [comment]
Can you let me know if this works:  https://www.npmjs.com/package/bulma-scss

I'm new to npm.

**Comment by j1mc** [comment]
It should show as published with this version under the bulma-scss npm package. If you encounter any difficulties in using it via npm, please report-back an issue here, and I'll check it out.

https://www.npmjs.com/package/bulma-scss

**Comment by ediopia** [comment]
It works pretty well.
Thanks for your contribution.
